spring:
  application:
    name: produto-service

  rabbitmq:
    port: 5672
    addresses: amqps://voowobdz:oPXu8xSnc3nXS_GlD6QR2wg9nz1afCdY@jackal.rmq.cloudamqp.com/voowobdz

  datasource:
    url: jdbc:postgresql://localhost:9007/produtos
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 7777